### PR TITLE
examples: add golang example for Travis CI

### PR DESCRIPTION
**Pull request by bbqtd**

### CODE REVIEW

**Comment by ale7714** [comment]
@bbqtd 👋  thanks for trying out the `test-reporter` and for contributing with an example. This looks great! Before merging, I wanted to check-in with you if you had any questions I could help with.

**Comment by bbqtd** [comment]
It's works. You could check travis builds [for instance](https://travis-ci.org/bbqtd/rg-kit/builds/329211541). I think you didn't use `master`. The coverage for multiple packages is implemented at `master` and going to be released in go 1.10

```
# The coverprofile for multiple packages works in go 1.10
# see https://tip.golang.org/doc/go1.10#test
go:
  - master
```

**Comment by nzin** [comment]
I see, thanks for the info!

**Comment by ale7714** [comment]
@bbqtd thanks for sharing that info! and thanks again for the example.

**Pull request merged**
