### PR TITLE
WIP gzip

### PR DESCRIPTION
**Pull request by markbates**
gzip request body #82

### CODE REVIEW

**Comment by markbates** [comment]
This is a WIP PR. I'm posting it because I appear to be getting a `500` error when hitting the API, which is unusual. The response doesn't tell me anything about what the error was.

If someone could let me know what the error is, it would go a long way to figure out what the fix is. :)

**Comment by ale7714** [comment]
About the error we got:
```
Zlib::GzipFile::ErrorPOST /test_reports
unexpected end of file
```
Request Header: 
```
{
  "Content-Type": "application/json",
  "Content-Length": "10",
  "User-Agent": "TestReporter/ (Code Climate, Inc.)",
  "Content-Encoding": "gzip",
  "Accept-Encoding": "gzip",
  "X-Forwarded-Proto": "https",
  "X-Forwarded-Port": "443",
  "X-Amzn-Trace-Id": "Root=1-58dd58da-6e1c37b9327a597b2a469078",
  "Host": "codeclimate.com",
  "X-Request-Start": "t=1490901210.470",
  "X-Forwarded-For": "108.7.199.241",
  "Version": "HTTP/1.1",
  "X-Middleware-Start": "t=1490901210470964"
}
```

**Comment by ale7714** [comment]
@markbates we just got this error 

```
Zlib::GzipFile::ErrorPOST /test_reports
not in gzip format

lib/code_climate/middleware/inflate.rb:42:in `initialize': not in gzip format (Zlib::GzipFile::Error)
    from lib/code_climate/middleware/inflate.rb:42:in `new'
    from lib/code_climate/middleware/inflate.rb:42:in `decode_gzip'
    from lib/code_climate/middleware/inflate.rb:32:in `decode'
    from lib/code_climate/middleware/inflate.rb:19:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from lib/code_climate/middleware/theory.rb:31:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
    from gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
    from gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
    from gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
    from gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from lib/code_climate/canonical_host_redirector.rb:13:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
    from gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
    from gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
    from gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
    from gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
    from gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:122:in `block in call'
    from gems/rack-timeout-0.4.2/lib/rack/timeout/support/timeout.rb:19:in `call'
    from gems/rack-timeout-0.4.2/lib/rack/timeout/support/timeout.rb:19:in `timeout'
    from gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:121:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from lib/code_climate/middleware_timer.rb:11:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
    from gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
    from gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
    from gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from gems/rack-attack-4.3.1/lib/rack/attack.rb:106:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/out_of_band_gc.rb:48:in `call'
    from gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
    from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
    from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
    from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
    from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

Request header

```
	
{
  "Content-Length": "752",
  "User-Agent": "TestReporter/ (Code Climate, Inc.)",
  "Content-Encoding": "gzip",
  "Accept-Encoding": "gzip",
  "X-Forwarded-Proto": "https",
  "X-Forwarded-Port": "443",
  "X-Amzn-Trace-Id": "Root=1-58e68338-26972d8b4fd4157b657da5d4",
  "Host": "codeclimate.com",
  "X-Request-Start": "t=1491501880.102",
  "X-Forwarded-For": "108.7.199.241",
  "Version": "HTTP/1.1",
  "X-Middleware-Start": "t=1491501880103926"
}
```

**Comment by markbates** [comment]
Thanks @ale7714 I was just going to ask for that. :)

**Comment by markbates** [comment]
So I'm at a bit of a loss. If I fire up a server locally and push the gzipped results to that it unzips fine on the server. However, when I push to codeclimate.com I get 500s. :(

Here is my local server code:

```go
package main

import (
	"compress/gzip"
	"io"
	"log"
	"net/http"
	"os"
)

func main() {
	http.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
		defer req.Body.Close()
		if req.Header.Get("Content-Encoding") == "gzip" {
			gr, err := gzip.NewReader(req.Body)
			if err != nil {
				os.Stderr.WriteString(err.Error())
				res.WriteHeader(500)
				return
			}
			io.Copy(os.Stdout, gr)
		} else {
			io.Copy(os.Stdout, req.Body)
		}
		res.WriteHeader(200)
	})
	log.Fatal(http.ListenAndServe(":3000", nil))
}
```

I'm open for suggestions and ideas.

**Comment by ale7714** [comment]
@markbates this our nginx conf for gzip

```
gzip              on;
gzip_vary         on;
gzip_http_version 1.0;
gzip_comp_level   2;
gzip_proxied      any;
gzip_buffers      16 8k;
gzip_types        application/json text/plain text/css application/x-javascript text/xml application/xml application/rss+xml text/javascript;
```

And to decode it we do

```ruby
      def decode_gzip(input)
        # Passenger expects to close the input itself, and complains loudly if
        # anybody else does. GzipReader closes its own input stream, so we read
        # the input into a separate, temporary IO object so everybody's happy
        strio = StringIO.new(input.read)
        reader = Zlib::GzipReader.new(strio)
        decoded = reader.read
        reader.close
        decoded
      end
```

**Comment by markbates** [comment]
@ale7714 @noahd1 @GordonDiggs closing this as per our discussion on monday.

**Pull request closed without merging**
