### PR TITLE
Update README with linux ARM64 links

### PR DESCRIPTION
**Pull request by camillof**
Now that ARM64 binaries have been uploaded, update the README so they are visible to users.

### CODE REVIEW

**Review by f-moya — APPROVED** [review]
👍🏼

**Comment by mrmachine** [comment]
The README `${VERSION}` link text for arm64 still says amd64, and the latest release version (0.10.3) listed in GitHub Releases (https://github.com/codeclimate/test-reporter/releases) and the docs (https://docs.codeclimate.com/docs/configuring-test-coverage#locations-of-pre-built-binaries) doesn't exist for arm64. I had to use `latest` (which did work, but I did not know what version it was) or by chance tried `0.10.4` which worked.

**Comment by camillof** [comment]
> The README `${VERSION}` link text for arm64 still says amd64, and the latest release version (0.10.3) listed in GitHub Releases (https://github.com/codeclimate/test-reporter/releases) and the docs (https://docs.codeclimate.com/docs/configuring-test-coverage#locations-of-pre-built-binaries) doesn't exist for arm64. I had to use `latest` (which did work, but I did not know what version it was) or by chance tried `0.10.4` which worked.

Hey @mrmachine I really appreciate this, the arm64 was the last platform we released and I forgot to update those references (and the typo!)

- Typo fix: https://github.com/codeclimate/test-reporter/pull/505
- Release on GH releases: https://github.com/codeclimate/test-reporter/releases/tag/0.10.4
- And also updated the docs: https://docs.codeclimate.com/docs/configuring-test-coverage

Again, thanks!!

**Comment by mrmachine** [comment]
Thank you for the arm release, and the quick update! 👍

**Pull request merged**
