### PR TITLE
Environment hash #49

### PR DESCRIPTION
**Pull request by markbates**
Related to #49

### CODE REVIEW

**Comment by pbrisbin** [comment]
In #49 I also show that `gem_version: "2.8.2"` should not be present. Where is that coming from?

**Comment by pbrisbin** [comment]
Oh! I didn't even realize you were actually giving us the real `gem --version`. Feel free to keep that code, but it was only useful when payloads were being submitted by our ruby-test-reporter (which was a gem) and its behavior might've been influenced by the verson of `gem` it was run with.

**Comment by markbates** [comment]
I'll change the way I get the version info. This was the "simple" way of doing it because of cyclical dependencies. I'll move the version stuff to it's own package that can be called by everyone.

**Comment by markbates** [comment]
@pbrisbin please re-review this.

**Comment by pbrisbin** [comment]
This is definitely better, having `FormattedVersion()` available wherever will be useful elsewhere: e.g. in the UserAgent for `upload-coverage`.

**Pull request merged**
