### PR TITLE
Add simplecov 0.18 support

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This is just an experiment to try to learn some `go` and fix https://github.com/codeclimate/test-reporter/issues/413 as a side effect.

This is not ready (I assume I would at least need to add back support for simplecov 0.17 or lower), and maybe it's not even correct :man_shrugging:, but it should be a start.

It seems to be working properly for me in https://github.com/deivid-rodriguez/byebug/pull/646.

### CODE REVIEW

**Comment by PragTob** [comment]
:wave: 

Not to spook in here as the old grumpy fellow (btw. :wave:  @deivid-rodriguez :green_heart: ) but imo this doesn't really _fix_ the problems. It returns the working state to what it was before, yes.
However, I'm still rather likely to change the format again (right now we need to evil `eval` things which I'm not too fond off) plus the other problems with skipping, filtering and adding files described in #413 are still there.

**Comment by deivid-rodriguez** [comment]
Well, the previous state worked pretty well for me, and I guess for other people too, so I think going back to the previous working state seems like a good move anyways, regardless of trying to figure out a better integration? I mean, without this PR I can no longer get diff and total coverage enforced in my PRs and use simplecov 0.18 at the same time. With this PR I can.

Things could be improved with extra stuff like the things you mentioned in #413's first post, sure! Does that justify not fixing the current integration in favour of a future better integration? Not so sure...

**Comment by PragTob** [comment]
@deivid-rodriguez I'm not saying this shouldn't be merging. I thinks it's great you did it and it's nice. 

My intention was to remind people that this doesn't really "fix" #413 (as in no further work to do there) - it fixes part of the problems described and it's somewhat likely to break again (due to https://github.com/colszowka/simplecov/issues/801 and whatever thing is done to adjust it).
I'd rather it not be forgotten, because then in the future the other problems persist and whenever we change the file format CodeClimate has to play catch up again :woman_shrugging: : 

Moreover, this would probably have to be amended to also support the format < 0.18.x (or add some kind of version constraint).

**Comment by deivid-rodriguez** [comment]
> @deivid-rodriguez I'm not saying this shouldn't be merging. I thinks it's great you did it and it's nice.

> My intention was to remind people that this doesn't really "fix" #413 (as in no further work to do there) - it fixes part of the problems described and it's somewhat likely to break again (due to colszowka/simplecov#801 and whatever thing is done to adjust it).

> I'd rather it not be forgotten, because then in the future the other problems persist and whenever we change the file format CodeClimate has to play catch up again :woman_shrugging:

Oh, sorry @PragTob, I misunderstood you! Yeah, I think most people is aware of that at this point, but it's good to make an explicit remainder in this PR :+1:. 

> Moreover, this would probably have to be amended to also support the format < 0.18.x (or add some kind of version constraint).

Yup, I mentioned this in the PR description, and I'm planning two amend the PR like that, indeed.

**Comment by PragTob** [comment]
> Oh, sorry @PragTob, I misunderstood you! Yeah, I think most people is aware of that at this point, but it's good to make an explicit remainder in this PR +1.

No problem, I could have probably expressed my intent clearer in my initial comment. Glad we sorted this out :crossed_fingers: 

Also sorry for missing your initial comment on the 0.17 support.

**Comment by deivid-rodriguez** [comment]
I restored simplecov 0.17 support. Now I'm working on learning some more about golang to be able to make the patch a bit more DRY and simpler.

**Comment by williamweckl** [comment]
Any updates on this one?

**Comment by elizabrock** [comment]
@deivid-rodriguez Since you added the 0.17 support, is this ready for prime time?  I'm hoping that if you update the PR description and sign the contributor agreement, they'll get this merged in soon :)

**Comment by deivid-rodriguez** [comment]
From what I understood, this is not going to get merged, because an alternative solution will be implemented :man_shrugging:.

**Comment by elizabrock** [comment]
@deivid-rodriguez. My interpretation of the conversation is that the maintainer of SimpleCov (@PragTob) commented here to say that while solution works, but that it isn't future-proof.  Like you, I think that we would all benefit from getting a working implementation and then proceeding from there.

I don't think that any of the maintainers of codeclimate/test-reporter (e.g. @davehenton ) have chimed in yet.  

My suspicion is that they are waiting to chime in until the PR has passed all of the automated checks, one of which is now signing the contributor license agreement.  So, I am hoping that if you sign the agreement and update your PR description to indicate that the work is complete, this PR will proceed along from there :)

**Comment by deivid-rodriguez** [comment]
I have no idea, honestly. Last time I checked, this PR was working but I was not fully satisfied with the implementation. I'm no longer using this library, but if maintainers express their intention to merge this, I'm happy to sign the CLA, and even trying to dedicate a bit more time to it.

**Comment by deivid-rodriguez** [comment]
Just to be sure, did you read https://github.com/codeclimate/test-reporter/issues/413? That's where I got my conclusions from.

**Comment by elizabrock** [comment]
Ah, I see what you are saying now, @deivid-rodriguez!  That issue has progressed since the last time I read it

**Comment by PragTob** [comment]
(FWIW @deivid-rodriguez is also a simplecov maintainer :smile: :green_heart: )

**Comment by williamweckl** [comment]
Any updated on this?

**Comment by PragTob** [comment]
👋 

I don't think it's likely that this will be adjusted and merged at this point. CodeClimate went ahead and created a JSON formatter which we're about to integrate in simplecov: https://github.com/simplecov-ruby/simplecov/pull/923

That will then return a structure code climate can rely upon.

**Comment by deivid-rodriguez** [comment]
Thanks for the heads up!

**Pull request closed without merging**
